ALTER SEQUENCE chat_group_sequence RESTART WITH 100;
ALTER SEQUENCE hibernate_sequence RESTART WITH 100;
ALTER SEQUENCE message_sequence RESTART WITH 100;
ALTER SEQUENCE user_group_sequence RESTART WITH 100;
ALTER SEQUENCE user_sequence RESTART WITH 100;